-- Create shopkeeper_inventory table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.shopkeeper_inventory (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    shopkeeper_id UUID NOT NULL REFERENCES public.shopkeepers(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    rarity TEXT NOT NULL DEFAULT 'common',
    base_price INTEGER NOT NULL DEFAULT 0,
    price_adjustment_percent INTEGER NOT NULL DEFAULT 0,
    final_price INTEGER NOT NULL DEFAULT 0,
    stock_quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_shopkeeper_inventory_shopkeeper_id 
ON public.shopkeeper_inventory(shopkeeper_id);

-- Update shop_type column to be TEXT instead of enum (if it's currently an enum)
-- This allows for flexible shop types generated by LLM
DO $$ 
BEGIN
    -- Check if shop_type is an enum and convert to TEXT
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'shopkeepers' 
        AND column_name = 'shop_type' 
        AND data_type = 'USER-DEFINED'
    ) THEN
        ALTER TABLE public.shopkeepers 
        ALTER COLUMN shop_type TYPE TEXT;
    END IF;
END $$;

-- Ensure shop_type column exists and is TEXT
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'shopkeepers' 
        AND column_name = 'shop_type'
    ) THEN
        ALTER TABLE public.shopkeepers 
        ADD COLUMN shop_type TEXT;
    END IF;
END $$;
